# Logstash 9.x - doğru API ayarları
api.http.host: "0.0.0.0"
api.http.port: 9600

# Pipeline reload (lokal dev için güzel)
config.reload.automatic: true
config.reload.interval: 3s

# Log seviyesi
log.level: info

# X-Pack monitoring'i şimdilik kapat (prod'da ayrıca açarız)
xpack.monitoring.enabled: false